- name: 1.分发kubelet-ssl
  copy: 
    src: /etc/kubernetes/ 
    dest: /etc/kubernetes/
- name: 2.清理无效的证书
  shell: "cd /etc/kubernetes/ssl/ && ls |grep '^kubelet'|while read i;do mv $i $i.bak;done"
  ignore_errors: yes
- name: 3.复制kubelet.config.json
  template:
    src: ../templates/kubelet.config.json.j2
    dest: /etc/kubernetes/kubelet.config.json
- name: 4.创建{{k8s_install_home}}/kubernetes目录
  file:
    path: "{{k8s_install_home}}/kubernetes/kubelet"
    state: directory
- name: 5.生成kubelet服务启动文件
  template:
    src: ../templates/kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
- name: 6.设置服务开机自启动
  shell: "systemctl enable kubelet"
- name: 7.启动kubelet服务
  systemd:
    daemon_reload: true
    name: kubelet
    state: restarted
    enabled: true
