- name: delete uninstall files, please wait...
  wait_for:
    timeout: 10
- service:
    name: flanneld
    state: stopped
    enabled: false
  ignore_errors: yes
- file:
    path: /etc/systemd/system/flanneld.service
    state: absent
  ignore_errors: yes
- file:
    path: /usr/local/bin/{{item}}
    state: absent
  with_items:
    - flannel
    - flanneld
    - ipvlan
    - ptp
    - vlan
    - bridge
    - bandwidth
    - loopback
    - dhcp
    - firewall
    - host-device
    - host-local
    - macvlan
    - static
    - sbr
    - portmap
    - mk-docker-opts.sh
    - tuning
    - kube-proxy
    - kubelet
    - kubectl
    - kube-install
  ignore_errors: yes
- file:
    path: /etc/kubernetes/ssl
    state: absent
  ignore_errors: yes
- file:
    path: /etc/kubernetes
    state: absent
  ignore_errors: yes
- file:
    path: /etc/cni
    state: absent
  ignore_errors: yes
- file:
    path: "{{software_home}}"
    state: absent
  ignore_errors: yes


