- name: 1.清理历史安装垃圾
  shell: ls /usr/bin/dockerd
  ignore_errors: yes
  register: result
- shell: rpm -e docker-ce-19.03.8-3.el7.x86_64 docker-ce-cli-19.03.8-3.el7.x86_64 containerd.io-1.2.13-3.1.el7.x86_64
  when: result|succeeded
- shell: echo "暂未发现历史安装垃圾"
  when: result|failed
- name: 2.创建基础包
  file:
    path: "{{ansible_home}}"
    state: directory
- name: 3.解压基础包
  #包含telnet expect ntp ipvsadm curl net-tools lrzsz gcc gcc-c++ yum-utils psmisc pcre-devel openssl-devel wget tree vim conntrack ipset sysstat libseccomp device-mapper-persistent-data lvm2 lsof traceroute containerd.io docker-ce docker-ce-cli
  unarchive:
    src: "{{ansible_home}}/pkg/basepkg.tar.gz"
    dest: "{{ansible_home}}"
    mode: 0744
- name: 4.安装基础包
  shell: "rpm -Uvh {{ansible_home}}/basepkg/*.rpm --force"
- name: 5.关闭防火墙
  service: 
    name: firewalld 
    state: stopped 
    enabled: no
- name: 6.临时停止selinux
  shell: "setenforce 0"
  ignore_errors: yes
- name: 7.关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
- name: 8.关闭postfix
  shell: "systemctl stop postfix && systemctl disable postfix"
- name: 9.设置系统limit
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{item}}"
  with_items:
    - '* soft nofile 65536'
    - '* hard nofile 65536'
    - '* soft nproc 65536'
    - '* hard nproc 65536'
    - '* soft memlock unlimited'
    - '* hard memlock unlimited'
- name: 10.生成ipvs_modules
  copy:
    src: ../templates/ipvs.modules
    dest: /etc/sysconfig/modules/
    mode: 0755
#- name: 10.增加nf_conntrack_ipv4参数配置
#  #如果你的操作系统是3.x内核，需要去掉本段的注释。
#  shell: "echo 'modprobe -- nf_conntrack_ipv4' >> /etc/sysconfig/modules/ipvs.modules"
- name: 11.运行ipvs_modules
  shell: "bash /etc/sysconfig/modules/ipvs.modules"
- name: 12.生成sysctl内核参数
  copy:
    src: ../templates/kubernetes.conf
    dest: /etc/sysctl.d/
#- name: 12.增加tcp_tw_recycle参数配置
#  #如果你的操作系统是3.x内核，需要去掉本段的注释。
#  shell: "echo 'net.ipv4.tcp_tw_recycle=0' >> /etc/sysctl.d/kubernetes.conf"
- name: 13.配置sysctl内核参数
  shell: sysctl -p /etc/sysctl.d/kubernetes.conf
- name: 14.创建journal目录
  file: 
    path: /var/log/journal
    state: directory
    mode: 0755
- name: 15.创建journald.conf.d目录
  file: 
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: 0755
- name: 16.生成prophet配置文件
  copy:
    src: ../templates/99-prophet.conf
    dest: /etc/systemd/journald.conf.d/
    mode: 0755
- name: 17.启动systemd-journald服务
  service:
    name: systemd-journald
    state: restarted
