- name: 1.等待30秒
  wait_for:
    timeout: 30
- name: 2.创建clusterrolebinding
  shell: "kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap"
  ignore_errors: yes
- shell: "kubectl create clusterrolebinding kube-apiserver:kubelet-apis --clusterrole=system:kubelet-api-admin --user kubernetes"
  ignore_errors: yes
- name: 3.显示kubelet-api-admin角色信息
  shell: "kubectl describe clusterrole system:node-bootstrapper"
  ignore_errors: yes
