- name: 1.生成kube-scheduler服务启动文件
  template:
    src: ../templates/kube-scheduler.service.j2
    dest: "/etc/systemd/system/kube-scheduler.service"
- name: 2.分发kube-scheduler证书
  copy: 
    src: /etc/kubernetes/
    dest: /etc/kubernetes/
- name: 3.生成{{k8s_install_home}}/kubernetes/kube-scheduler
  file: 
    path: "{{k8s_install_home}}/kubernetes/kube-scheduler/"
    state: directory
- name: 4.设置服务开机自启动
  shell: "systemctl enable kube-scheduler"
- name: 5.启动kube-scheduler服务
  systemd:
    daemon_reload: true
    name: kube-scheduler
    state: restarted
    enabled: true
