#- name: 1.yum install keepalived
#  yum: 
#    name: keepalived
#    state: latest
- name: 1.解压keepalived软件包
  unarchive:
    src: "{{ansible_home}}/pkg/keepalived.tar.gz"
    dest: "{{ansible_home}}"
    mode: 0744
- name: 2.安装keepalived软件
  shell: "rpm -Uvh {{ansible_home}}/keepalived/*.rpm --force"
- shell: "ip add|grep {{ip}}|awk '{print $NF}'"
  register: ens
- shell: "date"
- name: 3.生成keepalived配置
  template: 
    src: ../templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
- name: 4.生成check_http脚本
  template:
    src: ../templates/check_http.sh.j2
    dest: /etc/keepalived/check_http.sh
    mode: 0755
- name: 5.设置服务失败重试机制
  lineinfile:
    dest: /lib/systemd/system/keepalived.service 
    insertafter: '^KillMode=process'
    line: 'Restart=always'
- lineinfile:
    dest: /lib/systemd/system/keepalived.service 
    insertafter: '^KillMode=process'
    line: 'RestartSec=5'
- lineinfile:
    dest: /lib/systemd/system/keepalived.service 
    insertafter: '^After=syslog.target network-online.target'
    line: 'Requires=kube-apiserver.service'
- replace:
    path: /lib/systemd/system/keepalived.service 
    regexp: 'After=syslog.target network-online.target'
    replace: 'After=syslog.target network-online.target kube-apiserver.service etcd.service'
- name: 6.设置服务开机自启动
  shell: "systemctl enable keepalived"
- name: 7.启动keepalived服务
  systemd:
    daemon_reload: true
    name: keepalived
    state: restarted
    enabled: true
- name: 8.时间
  shell: date
