- name: 1.Decompress docker software package
  #包含ipvsadm ipset device-mapper-persistent-data lvm2 containerd.io docker-ce docker-ce-cli
  unarchive:
    src: "{{software_home}}/pkg/dockerpkg.tgz"
    dest: "{{software_home}}/temp"
    mode: 0744
- name: 2.Install docker software
  shell: "rpm -U {{software_home}}/temp/dockerpkg/*.rpm --force --nodeps"
- name: 3.Set docker config file
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    insertbefore: '^ExecStart=/usr/bin/dockerd'
    line: 'EnvironmentFile=/run/flannel/docker'
- name: 4.Set docker sock
  replace:
    path: /usr/lib/systemd/system/docker.service
    regexp: '--containerd=/run/containerd/containerd.sock'
    replace: '--containerd=/run/containerd/containerd.sock $DOCKER_NETWORK_OPTIONS'
- name: 5.Create docker configuration directory
  file:
    path: "/etc/docker"
    state: directory
- name: 6.Create docker configuration file
  template: 
    src: ../templates/daemon.json.j2
    dest: "/etc/docker/daemon.json"
