#如果你的服务器可以上公网，那么也可以采用注释的这大段来安装docker
#- name: 1.yum --add-repo
#  shell: "yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo"
#- name: 2.yum-config-manager --disable docker-ce-edge
#  shell: yum-config-manager --disable docker-ce-edge
#- name: 3.yum makecache fast
#  shell: yum makecache fast
#  args:
#    warn: False
#- name: 4.yum -y install docker-ce
#  yum:
#    name: docker-ce
#    state: latest
- name: 1.修改docker启动程序
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    insertbefore: '^ExecStart=/usr/bin/dockerd'
    line: 'EnvironmentFile=/run/flannel/docker'
- name: 2.修改docker的sock
  replace:
    path: /usr/lib/systemd/system/docker.service
    regexp: '--containerd=/run/containerd/containerd.sock'
    replace: '--containerd=/run/containerd/containerd.sock $DOCKER_NETWORK_OPTIONS'
- name: 3.创建docker配置目录
  file:
    path: "/etc/docker"
    state: directory
- name: 4.生成docker配置参数
  template: 
    src: ../templates/daemon.json.j2
    dest: "/etc/docker/daemon.json"
