- name: 1.Create k8s cert directory
  file:
    path: "/etc/kubernetes/ssl/"
    state: directory
- name: 2.Set kubernetes-csr configuration
  template:
    src: ../templates/kubernetes-csr.json.j2
    dest: "/etc/kubernetes/ssl/kubernetes-csr.json"
- copy:
    src: "../templates/{{item}}"
    dest: "/etc/kubernetes/ssl/{{item}}"
  with_items:
    - admin-csr.json
    - audit-policy.yaml
    - k8s-gencert.json
    - k8s-root-ca-csr.json
    - kube-proxy-csr.json
    - token.csv
- template:
    src: "../templates/{{item}}.j2"
    dest: "/etc/kubernetes/{{item}}"
  with_items:
    - ipvsinit_svc.yaml
    - ipvsinit_ep.yaml
- copy:
    src: "../templates/{{item}}"
    dest: "/etc/kubernetes/{{item}}"
  with_items:
    - apiserver-to-kubelet.yaml
    - cert-renew-rbac.yaml

