- name: 1.Decompress keepalived software package
  unarchive:
    src: "{{software_home}}/pkg/keepalived.tar.gz"
    dest: "{{software_home}}"
    mode: 0744
- name: 2.Install keepalived software
  shell: "rpm -U {{software_home}}/keepalived/*.rpm --force --nodeps"
- shell: "ip add|grep {{ip}}|awk '{print $NF}'"
  register: ens
- name: 3.Create keepalived configuration
  template: 
    src: ../templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
- name: 4.Create check_http shell
  template:
    src: ../templates/check_http.sh.j2
    dest: /etc/keepalived/check_http.sh
    mode: 0755
- name: 5.Set service failure retry mechanism
  lineinfile:
    dest: /lib/systemd/system/keepalived.service 
    insertafter: '^KillMode=process'
    line: 'Restart=always'
- lineinfile:
    dest: /lib/systemd/system/keepalived.service 
    insertafter: '^KillMode=process'
    line: 'RestartSec=5'
- lineinfile:
    dest: /lib/systemd/system/keepalived.service 
    insertafter: '^After=syslog.target network-online.target'
    line: 'Requires=kube-apiserver.service'
- replace:
    path: /lib/systemd/system/keepalived.service 
    regexp: 'After=syslog.target network-online.target'
    replace: 'After=syslog.target network-online.target kube-apiserver.service etcd.service'
- name: 6.Set service startup
  shell: "systemctl enable keepalived"
- name: 7.Start keepalived service
  systemd:
    daemon_reload: true
    name: keepalived
    state: restarted
    enabled: true

