- name: 1.Create kube-proxy.config.yaml configuration
  template: 
    src: ../templates/kube-proxy.config.yaml.j2
    dest: /etc/kubernetes/kube-proxy.config.yaml
- name: 2.Create {{k8s_install_home}}/kubernetes/kube-proxy directory
  file: 
    path: "{{k8s_install_home}}/kubernetes/kube-proxy"
    state: directory
- name: 3.Create kube-proxy service startup file
  template: 
    src: ../templates/kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
- name: 4.Set service startup
  shell: "systemctl enable kube-proxy"
- name: 5.Start kube-proxy service
  systemd:
    daemon_reload: true
    name: kube-proxy
    state: restarted
    enabled: true
