- name: 1.生成kube-proxy.config.yaml配置
  template: 
    src: ../templates/kube-proxy.config.yaml.j2
    dest: /etc/kubernetes/kube-proxy.config.yaml
- name: 2.创建{{k8s_install_home}}/kubernetes/kube-proxy
  file: 
    path: "{{k8s_install_home}}/kubernetes/kube-proxy"
    state: directory
- name: 3.生成kube-proxy服务启动文件
  template: 
    src: ../templates/kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
- name: 4.设置服务开机自启动
  shell: "systemctl enable kube-proxy"
- name: 5.启动kube-proxy服务
  systemd:
    daemon_reload: true
    name: kube-proxy
    state: restarted
    enabled: true
