- name: 1.Distribution kubelet cert
  copy: 
    src: "{{kipath}}/data/output{{sub_process_dir}}/cert/"
    dest: /etc/kubernetes/
- name: 2.Clean up invalid certificates
  shell: "cd /etc/kubernetes/ssl/ && ls |grep '^kubelet'|while read i;do mv $i /etc/kubernetes/bak/$i.bak;done"
  ignore_errors: yes
- name: 3.Copy kubelet.config.json
  template:
    src: "../templates/kubelet.config.json-{{k8sver}}.j2"
    dest: /etc/kubernetes/kubelet.config.json
- name: 4.Set IPVS rules
  shell: "/usr/local/bin/ipvsinit.sh"
  ignore_errors: yes
- name: 5.Create {{k8s_install_home}}/kubernetes directory
  file:
    path: "{{k8s_install_home}}/kubernetes/kubelet"
    state: directory
- name: 6.Create kubelet service startup file
  template:
    src: "../templates/kubelet.service-{{k8sver}}.j2"
    dest: /etc/systemd/system/kubelet.service
- name: 7.Set service startup
  shell: "systemctl enable kubelet"
- name: 8.Start kubelet service
  systemd:
    daemon_reload: true
    name: kubelet
    state: restarted
    enabled: true
