- name: 1.分发kube-apiserver证书
  copy: 
    src: /etc/kubernetes/
    dest: /etc/kubernetes/
- name: 2.生成kube-apiserver服务启动文件
  template:
    src: ../templates/kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
- name: 3.创建{{k8s_install_home}}/kubernetes/kube-apiserver
  file: 
    path: "{{k8s_install_home}}/kubernetes/kube-apiserver/log"
    state: directory
- name: 4.设置服务开机自启动
  shell: "systemctl enable kube-apiserver"
- name: 5.启动kube-apiserver服务
  systemd:
    daemon_reload: true
    name: kube-apiserver
    state: restarted
    enabled: true
- name: 6.时间
  shell: date
