- name: 1.Distribution kube-apiserver cert
  copy: 
    src: "{{kipath}}/data/output{{sub_process_dir}}/cert/"
    dest: /etc/kubernetes/
- name: 2.Create kube-apiserver service startup file
  template:
    src: "../templates/kube-apiserver.service-{{k8sver}}.j2"
    dest: /etc/systemd/system/kube-apiserver.service
- name: 3.Create {{k8s_install_home}}/kubernetes/kube-apiserver directory
  file: 
    path: "{{k8s_install_home}}/kubernetes/kube-apiserver/log"
    state: directory
- name: 4.Start kube-apiserver service
  systemd:
    daemon_reload: true
    name: kube-apiserver
    state: restarted
    enabled: true
- name: 5.Set IPVS rules
  shell: "/usr/local/bin/ipvsinit.sh"
  ignore_errors: yes

