- name: 1.Stop kubelet service
  service:
    name: kubelet
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 2.Stop kube-proxy service
  service:
    name: kube-proxy
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 3.Stop docker service
  service:
    name: docker
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 4.Uninstall docker software
  copy: 
    src: ../templates/uninstall-docker.sh
    dest: "{{software_home}}/temp/uninstall-docker.sh"
    mode: 0755
  ignore_errors: yes
- shell: "{{software_home}}/temp/uninstall-docker.sh"
  ignore_errors: yes

