- name: 1.Wait 30s
  wait_for:
    timeout: 30
- name: 2.Create clusterrolebinding
  shell: "kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap"
  ignore_errors: yes
- shell: "kubectl create clusterrolebinding kube-apiserver:kubelet-apis --clusterrole=system:kubelet-api-admin --user kubernetes"
  ignore_errors: yes
- name: 3.Get kubelet-api-admin role info
  shell: "kubectl describe clusterrole system:node-bootstrapper"
  ignore_errors: yes
