- name: 1.Create /root/.kube directory
  file: 
    path: /root/.kube
    state: directory
- name: 2.Create local.kubeconfig file
  copy:
    src: "{{kipath}}/data/output{{sub_process_dir}}/cert/ssl/local.kubeconfig"
    dest: "/root/.kube/config"
- name: 3.Generate kubectl program file
  shell: "cp -rf /usr/local/bin/kubectl /usr/sbin/"
  ignore_errors: yes

