apiVersion: v1
kind: Endpoints
metadata:
  name: ipvsinit-lb
  namespace: kube-system
  labels:
    k8sapp: ipvsinit-lb
subsets:
- addresses:
  - ip: 192.168.1.15 
  ports:
  - name: k8s-api
    port: 6443
    protocol: TCP
