- name: 1.解压etcd软件包
  unarchive:
    src: "{{software_home}}/pkg/etcd-v3.3.18.tar.gz"
    dest: /usr/local/bin/
    mode: 0755
- name: 2.创建{{k8s_install_home}}/etcd数据目录
  file: 
    path: "{{k8s_install_home}}/etcd"
    state: directory
- name: 3.创建etcd证书目录
  file: 
    path: /etc/kubernetes/ssl/
    state: directory
- name: 4.生成etcd服务启动文件
  template:
    src: ../templates/etcd.service.j2 
    dest: /etc/systemd/system/etcd.service
- name: 5.分发etcd证书
  copy: 
    src: /etc/kubernetes/
    dest: /etc/kubernetes/
- name: 6.设置服务开机自启动
  shell: "systemctl enable etcd"
- name: 7.启动etcd集群服务
  systemd:
    daemon_reload: true
    name: etcd
    state: restarted
    enabled: true
