- name: 1.创建内核包
  file:
    path: "{{software_home}}/temp"
    state: directory
- name: 2.解压内核包
  #update os to kernel4.19
  unarchive:
    src: "{{software_home}}/pkg/kernel4.19.tar.gz"
    dest: "{{software_home}}"
    mode: 0744
- name: 3.更新内核和grub配置
  template: 
    src: ../templates/updategrub.sh.j2
    dest: "{{software_home}}/temp/updategrub.sh"
    mode: 0755
- shell: "/bin/bash {{software_home}}/temp/updategrub.sh"
