- name: Congratulations, k8s cluster has been deployed! The operating system will automatically restart in 300 seconds to take effect on the cluster configuration. If you do not want to restart now, you can also directly press "Ctrl+C" to exit.
  shell: "date"
- file:
    path: "{{software_home}}/temp"
    state: directory
- copy:
    src: ../../templates/tempreboot.sh
    dest: "{{software_home}}/temp/tempreboot.sh"
    mode: 0755
- wait_for:
    timeout: 250
- shell: "nohup {{software_home}}/temp/tempreboot.sh 2>&1 &"
  ignore_errors: yes
