- name: 1.生成flanneld-csr.json配置
  copy: 
    src: ../templates/flanneld-csr.json.j2
    dest: "{{ansible_home}}/cert/flanneld-csr.json"
- name: 2.生成flanneld证书
  shell: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes flanneld-csr.json | cfssljson -bare flanneld chdir={{ansible_home}}/cert"
- name: 3.将flanneld证书移植到证书目录
  shell: "cp {{ansible_home}}/cert/flanneld*pem /etc/kubernetes/ssl"
####
- name: 4.在etcd中创建flannel网段
  shell: etcdctl --endpoints=https://{{etcd1}}:2379,https://{{etcd2}}:2379,https://{{etcd3}}:2379 --ca-file=/etc/kubernetes/ssl/ca.pem --cert-file=/etc/kubernetes/ssl/flanneld.pem --key-file=/etc/kubernetes/ssl/flanneld-key.pem set /kubernetes/network/config '{"Network":"{{pod_cidr}}", "SubnetLen":24, "Backend":{"Type":"vxlan"}}'
- name: 5.flannel网络配置结束
  command: date
