- name: 1.Create {{software_home}} directory
  file:
    path: "{{software_home}}/{{item}}"
    state: directory
  with_items:
    - bin
    - docs
    - pkg
    - proc
    - config
    - yaml
- name: 2.Distributing deployment files to kubernetes master, please wait...
  copy:
    src: "/root/kube-install/bin"
    dest: "{{software_home}}/"
- copy:
    src: "/root/kube-install/docs"
    dest: "{{software_home}}/"
- copy:
    src: "/root/kube-install/pkg"
    dest: "{{software_home}}/"
- copy:
    src: "/root/kube-install/proc"
    dest: "{{software_home}}/"
- copy:
    src: "/root/kube-install/config"
    dest: "{{software_home}}/"
- copy:
    src: "/root/kube-install/yaml"
    dest: "{{software_home}}/"
- copy:
    src: "/root/kube-install/kube-install"
    dest: "{{software_home}}/"
- copy:
    src: "/root/kube-install/kube-install"
    dest: "/usr/local/bin/kube-install"
    mode: 0755
- name: 3.Configure permissions for executables
  file: path={{software_home}}/{{ item }} mode=755 owner=root group=root
  with_items:
    - proc/sshkey-init.sh
    - proc/sshops-init.sh
    - proc/getmasterconfig.sh
- name: 4.Install distributed control software
  shell: "{{software_home}}/proc/sshops-init.sh {{software_home}} {{software_home}}"
  ignore_errors: yes

