- name: 1.Stop kube-controller-manager service
  service:
    name: kube-controller-manager
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 2.Stop kube-scheduler service
  service:
    name: kube-scheduler
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 3.Stop kube-apiserver service
  service:
    name: kube-apiserver
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 4.Stop etcd service
  service:
    name: etcd
    state: stopped
    enabled: false
  ignore_errors: yes
- name: 5.Delete kube-controller-manager file
  file:
    path: /etc/systemd/system/kube-controller-manager.service
    state: absent
  ignore_errors: yes
- file:
    path: /usr/local/bin/kube-controller-manager
    state: absent
  ignore_errors: yes
- name: 6.Delete kube-scheduler file
  file:
    path: /etc/systemd/system/kube-scheduler.service
    state: absent
  ignore_errors: yes
- file:
    path: /usr/local/bin/kube-scheduler
    state: absent
  ignore_errors: yes
- name: 7.Delete kube-apiserver file
  file:
    path: /etc/systemd/system/kube-apiserver.service
    state: absent
  ignore_errors: yes
- file:
    path: /usr/local/bin/{{item}}
    state: absent
  with_items:
    - apiextensions-apiserver
    - kube-aggregator
    - kube-apiserver
  ignore_errors: yes
- name: 8.Delete etcd file
  file:
    path: /etc/systemd/system/etcd.service 
    state: absent
  ignore_errors: yes
- file:
    path: /usr/local/bin/{{item}}
    state: absent
  with_items:
    - etcd
    - etcdctl
  ignore_errors: yes
- name: 9.Delete cfssl software file
  file:
    path: /usr/local/bin/{{item}}
    state: absent
  with_items:
    - cfssl
    - cfssl-certinfo
    - cfssljson
  ignore_errors: yes
- name: 10.Delete helm software file
  file:
    path: /usr/local/bin/helm
    state: absent
  ignore_errors: yes


