- name: 1.Create {{software_home}}/tools directory
  file:
    path: "{{software_home}}/tools"
    state: directory
### zlib
- name: 2.Decompress zlib software package
  unarchive:
    src: "{{software_home}}/pkg/zlib-1.2.11.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 3.Build and install zlib
  shell: "chdir={{software_home}}/tools/zlib-1.2.11 ./configure && make && make install"
### pcre
- name: 4.Decompress pcre software package
  unarchive:
    src: "{{software_home}}/pkg/pcre-8.43.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 5.Build and install pcre
  shell: "chdir={{software_home}}/tools/pcre-8.43 ./configure && make && make install"
### openssl
- name: 6.Decompress openssl software package
  unarchive:
    src: "{{software_home}}/pkg/openssl-1.0.2t.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 7.Build and install openssl
  shell: "chdir={{software_home}}/tools/openssl-1.0.2t ./config && make && make install"
### nginx
- name: 8.Decompress nginx software package
  unarchive:
    src: "{{software_home}}/pkg/nginx-1.16.1.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 9.Build and install nginx
  shell: "chdir={{software_home}}/tools/nginx-1.16.1 ./configure --prefix={{k8s_install_home}}/nginx --with-pcre --with-stream --with-threads --with-file-aio --with-http_v2_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_ssl_module --with-http_slice_module --with-stream_ssl_module --with-http_realip_module --with-http_gunzip_module --with-http_addition_module --with-http_secure_link_module --with-http_stub_status_module --with-http_gzip_static_module --with-http_random_index_module --with-http_auth_request_module --with-pcre={{software_home}}/tools/pcre-8.43 --with-zlib={{software_home}}/tools/zlib-1.2.11 --with-openssl={{software_home}}/tools/openssl-1.0.2t && make && make install"
- name: 10.Create nginx configuration file
  template:
    src: ../templates/nginx.conf.j2
    dest: "{{k8s_install_home}}/nginx/conf/nginx.conf"
- name: 11.Create nginx service startup file
  template:
    src: ../templates/nginx.service.j2
    dest: /etc/systemd/system/nginx.service
- name: 12.Set service startup
  shell: "systemctl enable nginx"
- name: 13.Start nginx service
  systemd:
    daemon_reload: true
    name: nginx
    state: restarted
    enabled: true
