- name: 1.创建{{software_home}}/tools目录
  file:
    path: "{{software_home}}/tools"
    state: directory
### zlib
- name: 2.解压zlib软件包
  unarchive:
    src: "{{software_home}}/pkg/zlib-1.2.11.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 3.编译安装zlib
  shell: "chdir={{software_home}}/tools/zlib-1.2.11 ./configure && make && make install"
### pcre
- name: 4.解压pcre软件包
  unarchive:
    src: "{{software_home}}/pkg/pcre-8.43.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 5.编译安装pcre
  shell: "chdir={{software_home}}/tools/pcre-8.43 ./configure && make && make install"
### openssl
- name: 6.解压openssl软件包
  unarchive:
    src: "{{software_home}}/pkg/openssl-1.0.2t.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 7.编译安装openssl
  shell: "chdir={{software_home}}/tools/openssl-1.0.2t ./config && make && make install"
### nginx
- name: 8.解压nginx软件包
  unarchive:
    src: "{{software_home}}/pkg/nginx-1.16.1.tar.gz"
    dest: "{{software_home}}/tools/"
    copy: yes
- name: 9.编译安装nginx
  shell: "chdir={{software_home}}/tools/nginx-1.16.1 ./configure --prefix={{k8s_install_home}}/nginx --with-pcre --with-stream --with-threads --with-file-aio --with-http_v2_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_ssl_module --with-http_slice_module --with-stream_ssl_module --with-http_realip_module --with-http_gunzip_module --with-http_addition_module --with-http_secure_link_module --with-http_stub_status_module --with-http_gzip_static_module --with-http_random_index_module --with-http_auth_request_module --with-pcre={{software_home}}/tools/pcre-8.43 --with-zlib={{software_home}}/tools/zlib-1.2.11 --with-openssl={{software_home}}/tools/openssl-1.0.2t && make && make install"
- name: 10.生成nginx配置文件
  template:
    src: ../templates/nginx.conf.j2
    dest: "{{k8s_install_home}}/nginx/conf/nginx.conf"
- name: 11.生成nginx服务启动文件
  template:
    src: ../templates/nginx.service.j2
    dest: /etc/systemd/system/nginx.service
- name: 12.设置服务开机自启动
  shell: "systemctl enable nginx"
- name: 13.启动nginx服务
  systemd:
    daemon_reload: true
    name: nginx
    state: restarted
    enabled: true
