apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.122.100:18080"
  restuser: "admin"
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:3"