apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
  labels:
    app: myapp
spec:
  replicas: 10
  template: 
    metadata:
      labels:
        app: myapp
    spec: 
      containers: 
        - name: myapp
          image: {{registry_ip}}:5000/nginx:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          env:
            - name: group
              value: cloudnativer
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 60
          #volumeMounts:
          #- name: nginx-conf-configmap
          #  mountPath: /etc/nginx/nginx.conf
          #  readOnly: True
          #  subPath: nginx.conf
          #- name: nginx-log
          #  mountPath: /var/logs/nginx
      #volumes:
      #  - name: nginx-log
      #    hostPath:
      #      path: /opt
      #  - name: nginx-conf-configmap
      #    configMap:
      #      name: nginx-conf-configmap
---
apiVersion: v1
kind: Service
metadata: 
  name: myapp
  namespace: myapp
  labels: 
    app: myapp
spec:
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp
  namespace: myapp
spec:
  rules:
  - host: myapp.nginx.com
    http:
       paths:
       - path:
         backend:
           serviceName: myapp
           servicePort: 80

