- name: 1.生成admin_login信息
  copy:
    src: "../templates/admin_login.txt"
    dest: "{{ansible_home}}/admin_login.txt"
- copy:
    src: "{{ansible_home}}/addons/temp/tokentmp"
    dest: "/etc/kubernetes/dashboard_login_token.txt"
- shell: "cat /etc/kubernetes/dashboard_login_token.txt >> {{ansible_home}}/admin_login.txt"
- name: 2.获取k8s-node信息
  shell: "kubectl get node|awk 'NR>1{print $1}'"
  register: nodes
- shell: "echo '{{nodes.stdout}}' > /opt/temp.txt"
- shell: "for node in `cat /opt/temp.txt`;do echo '        server '${node}':{{traefik_admin_port}} max_fails=3 fail_timeout=30s;' >> /opt/traefik.txt;done"
- shell: "cat /opt/traefik.txt"
  register: traefik
- name: 3.生成nginx配置
  #shell: 'sed -i "s/server 10.10.10.10;/`echo {{traefik.stdout}}`/" {{k8s_install_home}}/kubernetes/nginx/conf/nginx.conf'
  lineinfile:
    dest: "{{k8s_install_home}}/nginx/conf/nginx.conf"
    regexp: 'server 10.10.10.10;'
    line: '{{traefik.stdout}}'
- name: 4.删除旧文件
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /opt/temp.txt
    - /opt/traefik.txt
- name: 5.生成check_nginx脚本
  template:
    src: ../templates/check_http.sh.j2
    dest: /etc/keepalived/check_http.sh
    mode: 0755
- name: 6.启动nginx服务
  systemd:
    daemon_reload: true
    name: nginx
    state: restarted
    enabled: true
- name: 7.启动keepalived服务
  systemd:
    daemon_reload: true
    name: keepalived
    state: restarted
    enabled: true
