- name: 1.Get k8s-node info
  shell: "kubectl get node|awk 'NR>1{print $1}'"
  register: nodes
- shell: "echo '{{nodes.stdout}}' > /opt/temp.txt"
- shell: "for node in `cat /opt/temp.txt`;do echo '        server '${node}':{{traefik_admin_port}} max_fails=3 fail_timeout=30s;' >> /opt/traefik.txt;done"
- shell: "cat /opt/traefik.txt"
  register: traefik
- name: 2.Create nginx configuration
  #shell: 'sed -i "s/server 10.10.10.10;/`echo {{traefik.stdout}}`/" {{k8s_install_home}}/kubernetes/nginx/conf/nginx.conf'
  lineinfile:
    dest: "{{k8s_install_home}}/nginx/conf/nginx.conf"
    regexp: 'server 10.10.10.10;'
    line: '{{traefik.stdout}}'
- name: 3.Clean up unwanted files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /opt/temp.txt
    - /opt/traefik.txt
- name: 4.Create check_nginx shell
  template:
    src: ../templates/check_http.sh.j2
    dest: /etc/keepalived/check_http.sh
    mode: 0755
- name: 5.Start nginx service
  systemd:
    daemon_reload: true
    name: nginx
    state: restarted
    enabled: true
- name: 6.Start keepalived service
  systemd:
    daemon_reload: true
    name: keepalived
    state: restarted
    enabled: true
