- name: 1.Update check_nginx shell
  template:
    src: ../templates/check_http.sh.j2
    dest: /etc/keepalived/check_http.sh
    mode: 0755
- name: 2.Restart nginx service
  systemd:
    daemon_reload: true
    name: nginx
    state: restarted
    enabled: true
- name: 3,Restart keepalived service
  systemd:
    daemon_reload: true
    name: keepalived
    state: restarted
    enabled: true

